/**
 * Badge Collection System - Continued
 * Activity, Challenge, Seasonal, and Secret badges
 */

import type { Badge } from './badge-system';
import { RARITY_REWARDS } from './badge-system';

export const ACTIVITY_BADGES: Badge[] = [
  // ============================================
  // ACTIVITY BADGES (20 badges)
  // ============================================
  {
    id: 'artist-i',
    icon: '🎨',
    category: 'activity',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    series: 'artist',
    seriesOrder: 1,
    conditions: [{ type: 'count', metric: 'coloring_pages_completed', operator: '>=', value: 10 }],
    name: {
      de: 'Künstler I',
      ar: 'فنان I',
      en: 'Artist I',
      tr: 'Sanatçı I',
      ur: 'فنکار I',
    },
    description: {
      de: '10 Ausmalbilder fertiggestellt',
      ar: 'أكملت 10 صفحات تلوين',
      en: 'Complete 10 coloring pages',
      tr: '10 boyama sayfası tamamla',
      ur: '10 رنگ بھرنے کے صفحات مکمل کریں',
    },
    hint: {
      de: 'Male Bilder aus',
      ar: 'قم بتلوين الصور',
      en: 'Color pictures',
      tr: 'Resimleri boya',
      ur: 'تصاویر رنگ کریں',
    },
  },
  {
    id: 'artist-ii',
    icon: '🎨✨',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    series: 'artist',
    seriesOrder: 2,
    conditions: [{ type: 'count', metric: 'coloring_pages_completed', operator: '>=', value: 25 }],
    name: {
      de: 'Künstler II',
      ar: 'فنان II',
      en: 'Artist II',
      tr: 'Sanatçı II',
      ur: 'فنکار II',
    },
    description: {
      de: '25 Ausmalbilder fertiggestellt',
      ar: 'أكملت 25 صفحة تلوين',
      en: 'Complete 25 coloring pages',
      tr: '25 boyama sayfası tamamla',
      ur: '25 رنگ بھرنے کے صفحات مکمل کریں',
    },
    hint: {
      de: 'Male viele Bilder aus',
      ar: 'قم بتلوين العديد من الصور',
      en: 'Color many pictures',
      tr: 'Birçok resmi boya',
      ur: 'بہت سی تصاویر رنگ کریں',
    },
  },
  {
    id: 'musician-i',
    icon: '🎵',
    category: 'activity',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    series: 'musician',
    seriesOrder: 1,
    conditions: [{ type: 'count', metric: 'compositions_created', operator: '>=', value: 5 }],
    name: {
      de: 'Musiker I',
      ar: 'موسيقي I',
      en: 'Musician I',
      tr: 'Müzisyen I',
      ur: 'موسیقی کار I',
    },
    description: {
      de: '5 Musikstücke komponiert',
      ar: 'ألفت 5 مقطوعات موسيقية',
      en: 'Compose 5 music pieces',
      tr: '5 müzik parçası bestelemek',
      ur: '5 موسیقی کے ٹکڑے بنائیں',
    },
    hint: {
      de: 'Erstelle Musikstücke',
      ar: 'أنشئ مقطوعات موسيقية',
      en: 'Create music pieces',
      tr: 'Müzik parçaları oluştur',
      ur: 'موسیقی کے ٹکڑے بنائیں',
    },
  },
  {
    id: 'musician-ii',
    icon: '🎵✨',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    series: 'musician',
    seriesOrder: 2,
    conditions: [{ type: 'count', metric: 'compositions_created', operator: '>=', value: 15 }],
    name: {
      de: 'Musiker II',
      ar: 'موسيقي II',
      en: 'Musician II',
      tr: 'Müzisyen II',
      ur: 'موسیقی کار II',
    },
    description: {
      de: '15 Musikstücke komponiert',
      ar: 'ألفت 15 مقطوعة موسيقية',
      en: 'Compose 15 music pieces',
      tr: '15 müzik parçası bestelemek',
      ur: '15 موسیقی کے ٹکڑے بنائیں',
    },
    hint: {
      de: 'Komponiere mehr Musikstücke',
      ar: 'ألف المزيد من المقطوعات الموسيقية',
      en: 'Compose more music pieces',
      tr: 'Daha fazla müzik parçası bestele',
      ur: 'مزید موسیقی کے ٹکڑے بنائیں',
    },
  },
  {
    id: 'performer',
    icon: '🎭',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'puppet_shows_recorded', operator: '>=', value: 5 }],
    name: {
      de: 'Darsteller',
      ar: 'ممثل',
      en: 'Performer',
      tr: 'Oyuncu',
      ur: 'اداکار',
    },
    description: {
      de: '5 Puppentheater aufgenommen',
      ar: 'سجلت 5 عروض دمى',
      en: 'Record 5 puppet shows',
      tr: '5 kukla gösterisi kaydet',
      ur: '5 کٹھ پتلی شو ریکارڈ کریں',
    },
    hint: {
      de: 'Erstelle Puppentheater-Aufführungen',
      ar: 'أنشئ عروض مسرح الدمى',
      en: 'Create puppet theater performances',
      tr: 'Kukla tiyatrosu gösterileri oluştur',
      ur: 'کٹھ پتلی تھیٹر پرفارمنس بنائیں',
    },
  },
  {
    id: 'game-master',
    icon: '🎮',
    category: 'activity',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'games_played', operator: '>=', value: 50 }],
    name: {
      de: 'Spiele-Meister',
      ar: 'سيد الألعاب',
      en: 'Game Master',
      tr: 'Oyun Ustası',
      ur: 'گیم ماسٹر',
    },
    description: {
      de: '50 Spiele gespielt',
      ar: 'لعبت 50 لعبة',
      en: 'Play 50 games',
      tr: '50 oyun oyna',
      ur: '50 گیمز کھیلیں',
    },
    hint: {
      de: 'Spiele verschiedene Spiele',
      ar: 'العب ألعابًا مختلفة',
      en: 'Play different games',
      tr: 'Farklı oyunlar oyna',
      ur: 'مختلف گیمز کھیلیں',
    },
  },
  {
    id: 'puzzle-solver',
    icon: '🧩',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'puzzles_completed', operator: '>=', value: 20 }],
    name: {
      de: 'Puzzle-Löser',
      ar: 'حلال الألغاز',
      en: 'Puzzle Solver',
      tr: 'Bulmaca Çözücü',
      ur: 'پزل حل کرنے والا',
    },
    description: {
      de: '20 Puzzles gelöst',
      ar: 'حللت 20 لغزًا',
      en: 'Solve 20 puzzles',
      tr: '20 bulmaca çöz',
      ur: '20 پزل حل کریں',
    },
    hint: {
      de: 'Löse Jigsaw-Puzzles',
      ar: 'حل ألغاز الصور المقطوعة',
      en: 'Solve jigsaw puzzles',
      tr: 'Yapboz bulmacalarını çöz',
      ur: 'جگ سا پزل حل کریں',
    },
  },
  {
    id: 'memory-champion',
    icon: '🧠',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'memory_games_won', operator: '>=', value: 15 }],
    name: {
      de: 'Gedächtnis-Champion',
      ar: 'بطل الذاكرة',
      en: 'Memory Champion',
      tr: 'Hafıza Şampiyonu',
      ur: 'میموری چیمپئن',
    },
    description: {
      de: '15 Gedächtnisspiele gewonnen',
      ar: 'فزت بـ 15 لعبة ذاكرة',
      en: 'Win 15 memory games',
      tr: '15 hafıza oyunu kazan',
      ur: '15 میموری گیمز جیتیں',
    },
    hint: {
      de: 'Gewinne Gedächtnisspiele',
      ar: 'اربح ألعاب الذاكرة',
      en: 'Win memory games',
      tr: 'Hafıza oyunlarını kazan',
      ur: 'میموری گیمز جیتیں',
    },
  },
  {
    id: 'maze-explorer',
    icon: '🗺️',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'mazes_completed', operator: '>=', value: 10 }],
    name: {
      de: 'Labyrinth-Entdecker',
      ar: 'مستكشف المتاهات',
      en: 'Maze Explorer',
      tr: 'Labirent Kaşifi',
      ur: 'بھول بھلیاں کھوجی',
    },
    description: {
      de: '10 Labyrinthe abgeschlossen',
      ar: 'أكملت 10 متاهات',
      en: 'Complete 10 mazes',
      tr: '10 labirent tamamla',
      ur: '10 بھول بھلیاں مکمل کریں',
    },
    hint: {
      de: 'Löse Labyrinth-Rätsel',
      ar: 'حل ألغاز المتاهات',
      en: 'Solve maze puzzles',
      tr: 'Labirent bulmacalarını çöz',
      ur: 'بھول بھلیاں کے پزل حل کریں',
    },
  },
  {
    id: 'dancer',
    icon: '💃',
    category: 'activity',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    conditions: [{ type: 'count', metric: 'dance_games_played', operator: '>=', value: 10 }],
    name: {
      de: 'Tänzer',
      ar: 'راقص',
      en: 'Dancer',
      tr: 'Dansçı',
      ur: 'رقاصہ',
    },
    description: {
      de: '10 Tanzspiele gespielt',
      ar: 'لعبت 10 ألعاب رقص',
      en: 'Play 10 dance games',
      tr: '10 dans oyunu oyna',
      ur: '10 ڈانس گیمز کھیلیں',
    },
    hint: {
      de: 'Spiele Tanzspiele',
      ar: 'العب ألعاب الرقص',
      en: 'Play dance games',
      tr: 'Dans oyunları oyna',
      ur: 'ڈانس گیمز کھیلیں',
    },
  },
  {
    id: 'choreographer',
    icon: '🎭',
    category: 'activity',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'choreographies_created', operator: '>=', value: 5 }],
    name: {
      de: 'Choreograf',
      ar: 'مصمم رقصات',
      en: 'Choreographer',
      tr: 'Koreograf',
      ur: 'کوریوگرافر',
    },
    description: {
      de: '5 Choreografien erstellt',
      ar: 'أنشأت 5 تصميمات رقص',
      en: 'Create 5 choreographies',
      tr: '5 koreografi oluştur',
      ur: '5 کوریوگرافی بنائیں',
    },
    hint: {
      de: 'Erstelle eigene Tanz-Choreografien',
      ar: 'أنشئ تصميمات رقص خاصة بك',
      en: 'Create your own dance choreographies',
      tr: 'Kendi dans koreografilerini oluştur',
      ur: 'اپنی خود کی ڈانس کوریوگرافی بنائیں',
    },
  },
  {
    id: 'pet-parent',
    icon: '🐾',
    category: 'activity',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    conditions: [{ type: 'count', metric: 'pets_adopted', operator: '>=', value: 1 }],
    name: {
      de: 'Haustier-Eltern',
      ar: 'والد الحيوانات الأليفة',
      en: 'Pet Parent',
      tr: 'Evcil Hayvan Ebeveyni',
      ur: 'پالتو جانور کے والدین',
    },
    description: {
      de: 'Erstes Haustier adoptiert',
      ar: 'تبنيت أول حيوان أليف',
      en: 'Adopt first pet',
      tr: 'İlk evcil hayvanı evlat edin',
      ur: 'پہلا پالتو جانور اپنائیں',
    },
    hint: {
      de: 'Adoptiere ein virtuelles Haustier',
      ar: 'تبنى حيوانًا أليفًا افتراضيًا',
      en: 'Adopt a virtual pet',
      tr: 'Sanal bir evcil hayvan evlat edin',
      ur: 'ایک ورچوئل پالتو جانور اپنائیں',
    },
  },
  {
    id: 'pet-caretaker',
    icon: '💖',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'pet_care_actions', operator: '>=', value: 100 }],
    name: {
      de: 'Haustier-Pfleger',
      ar: 'مربي الحيوانات الأليفة',
      en: 'Pet Caretaker',
      tr: 'Evcil Hayvan Bakıcısı',
      ur: 'پالتو جانور کی دیکھ بھال کرنے والا',
    },
    description: {
      de: '100 Pflege-Aktionen durchgeführt',
      ar: 'قمت بـ 100 إجراء رعاية',
      en: 'Perform 100 care actions',
      tr: '100 bakım eylemi gerçekleştir',
      ur: '100 دیکھ بھال کے اقدامات کریں',
    },
    hint: {
      de: 'Kümmere dich um dein Haustier',
      ar: 'اعتن بحيوانك الأليف',
      en: 'Take care of your pet',
      tr: 'Evcil hayvanına bak',
      ur: 'اپنے پالتو جانور کی دیکھ بھال کریں',
    },
  },
  {
    id: 'character-designer',
    icon: '🎨',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'characters_designed', operator: '>=', value: 10 }],
    name: {
      de: 'Charakter-Designer',
      ar: 'مصمم الشخصيات',
      en: 'Character Designer',
      tr: 'Karakter Tasarımcısı',
      ur: 'کردار ڈیزائنر',
    },
    description: {
      de: '10 Charaktere erstellt',
      ar: 'أنشأت 10 شخصيات',
      en: 'Create 10 characters',
      tr: '10 karakter oluştur',
      ur: '10 کردار بنائیں',
    },
    hint: {
      de: 'Erstelle eigene Charaktere',
      ar: 'أنشئ شخصياتك الخاصة',
      en: 'Create your own characters',
      tr: 'Kendi karakterlerini oluştur',
      ur: 'اپنے خود کے کردار بنائیں',
    },
  },
  {
    id: 'story-creator',
    icon: '📝',
    category: 'activity',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'stories_created', operator: '>=', value: 5 }],
    name: {
      de: 'Geschichten-Schöpfer',
      ar: 'خالق القصص',
      en: 'Story Creator',
      tr: 'Hikaye Yaratıcısı',
      ur: 'کہانی بنانے والا',
    },
    description: {
      de: '5 eigene Geschichten erstellt',
      ar: 'أنشأت 5 قصص خاصة',
      en: 'Create 5 own stories',
      tr: '5 kendi hikayeni oluştur',
      ur: '5 اپنی کہانیاں بنائیں',
    },
    hint: {
      de: 'Nutze den Geschichten-Baukasten',
      ar: 'استخدم منشئ القصص',
      en: 'Use the story builder',
      tr: 'Hikaye oluşturucuyu kullan',
      ur: 'کہانی بنانے والا استعمال کریں',
    },
  },
  {
    id: 'fortune-seeker',
    icon: '🔮',
    category: 'activity',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    conditions: [{ type: 'count', metric: 'fortune_teller_uses', operator: '>=', value: 10 }],
    name: {
      de: 'Glückssucher',
      ar: 'باحث عن الحظ',
      en: 'Fortune Seeker',
      tr: 'Talih Arayıcı',
      ur: 'قسمت تلاش کرنے والا',
    },
    description: {
      de: 'Wahrsagerei 10 Mal genutzt',
      ar: 'استخدمت قارئ الطالع 10 مرات',
      en: 'Use fortune teller 10 times',
      tr: 'Falcıyı 10 kez kullan',
      ur: 'قسمت بتانے والے کو 10 بار استعمال کریں',
    },
    hint: {
      de: 'Besuche die Wahrsagerin',
      ar: 'قم بزيارة قارئة الطالع',
      en: 'Visit the fortune teller',
      tr: 'Falcıyı ziyaret et',
      ur: 'قسمت بتانے والے سے ملیں',
    },
  },
  {
    id: 'treasure-hunter',
    icon: '💎',
    category: 'activity',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'treasures_found', operator: '>=', value: 20 }],
    name: {
      de: 'Schatzjäger',
      ar: 'صائد الكنوز',
      en: 'Treasure Hunter',
      tr: 'Hazine Avcısı',
      ur: 'خزانہ شکاری',
    },
    description: {
      de: '20 Schätze gefunden',
      ar: 'وجدت 20 كنزًا',
      en: 'Find 20 treasures',
      tr: '20 hazine bul',
      ur: '20 خزانے تلاش کریں',
    },
    hint: {
      de: 'Erkunde die Geschichten-Karte',
      ar: 'استكشف خريطة القصص',
      en: 'Explore the story map',
      tr: 'Hikaye haritasını keşfet',
      ur: 'کہانی کے نقشے کو دریافت کریں',
    },
  },
  {
    id: 'card-collector',
    icon: '🃏',
    category: 'activity',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'cards_collected', operator: '>=', value: 50 }],
    name: {
      de: 'Karten-Sammler',
      ar: 'جامع البطاقات',
      en: 'Card Collector',
      tr: 'Kart Koleksiyoncusu',
      ur: 'کارڈ جمع کرنے والا',
    },
    description: {
      de: '50 Charakterkarten gesammelt',
      ar: 'جمعت 50 بطاقة شخصية',
      en: 'Collect 50 character cards',
      tr: '50 karakter kartı topla',
      ur: '50 کردار کارڈ جمع کریں',
    },
    hint: {
      de: 'Sammle Charakterkarten',
      ar: 'اجمع بطاقات الشخصيات',
      en: 'Collect character cards',
      tr: 'Karakter kartlarını topla',
      ur: 'کردار کارڈ جمع کریں',
    },
  },
  {
    id: 'shopaholic',
    icon: '🛍️',
    category: 'activity',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'shop_purchases', operator: '>=', value: 20 }],
    name: {
      de: 'Kaufrausch',
      ar: 'مدمن التسوق',
      en: 'Shopaholic',
      tr: 'Alışveriş Bağımlısı',
      ur: 'خریداری کا شوقین',
    },
    description: {
      de: '20 Artikel im Shop gekauft',
      ar: 'اشتريت 20 عنصرًا من المتجر',
      en: 'Purchase 20 items from shop',
      tr: 'Mağazadan 20 ürün satın al',
      ur: 'دکان سے 20 اشیاء خریدیں',
    },
    hint: {
      de: 'Kaufe Artikel im Sternenladen',
      ar: 'اشتر عناصر من متجر النجوم',
      en: 'Buy items from star shop',
      tr: 'Yıldız mağazasından ürünler satın al',
      ur: 'سٹار شاپ سے اشیاء خریدیں',
    },
  },
  {
    id: 'quest-adventurer',
    icon: '⚔️',
    category: 'activity',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'quests_completed', operator: '>=', value: 25 }],
    name: {
      de: 'Quest-Abenteurer',
      ar: 'مغامر المهمات',
      en: 'Quest Adventurer',
      tr: 'Görev Maceracısı',
      ur: 'کوئسٹ مہم جو',
    },
    description: {
      de: '25 Quests abgeschlossen',
      ar: 'أكملت 25 مهمة',
      en: 'Complete 25 quests',
      tr: '25 görevi tamamla',
      ur: '25 کوئسٹ مکمل کریں',
    },
    hint: {
      de: 'Schließe Quests ab',
      ar: 'أكمل المهمات',
      en: 'Complete quests',
      tr: 'Görevleri tamamla',
      ur: 'کوئسٹ مکمل کریں',
    },
  },
];

export const CHALLENGE_BADGES: Badge[] = [
  // ============================================
  // CHALLENGE BADGES (15 badges)
  // ============================================
  {
    id: 'daily-achiever',
    icon: '📆',
    category: 'challenge',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    conditions: [{ type: 'count', metric: 'daily_challenges_completed', operator: '>=', value: 7 }],
    name: {
      de: 'Täglicher Held',
      ar: 'بطل يومي',
      en: 'Daily Achiever',
      tr: 'Günlük Başarılı',
      ur: 'روزانہ حاصل کرنے والا',
    },
    description: {
      de: '7 tägliche Herausforderungen abgeschlossen',
      ar: 'أكملت 7 تحديات يومية',
      en: 'Complete 7 daily challenges',
      tr: '7 günlük meydan okumayı tamamla',
      ur: '7 روزانہ چیلنجز مکمل کریں',
    },
    hint: {
      de: 'Schließe tägliche Herausforderungen ab',
      ar: 'أكمل التحديات اليومية',
      en: 'Complete daily challenges',
      tr: 'Günlük meydan okumaları tamamla',
      ur: 'روزانہ چیلنجز مکمل کریں',
    },
  },
  {
    id: 'weekly-warrior',
    icon: '🗓️',
    category: 'challenge',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'weekly_challenges_completed', operator: '>=', value: 4 }],
    name: {
      de: 'Wöchentlicher Krieger',
      ar: 'محارب أسبوعي',
      en: 'Weekly Warrior',
      tr: 'Haftalık Savaşçı',
      ur: 'ہفتہ وار جنگجو',
    },
    description: {
      de: '4 wöchentliche Herausforderungen abgeschlossen',
      ar: 'أكملت 4 تحديات أسبوعية',
      en: 'Complete 4 weekly challenges',
      tr: '4 haftalık meydan okumayı tamamla',
      ur: '4 ہفتہ وار چیلنجز مکمل کریں',
    },
    hint: {
      de: 'Schließe wöchentliche Herausforderungen ab',
      ar: 'أكمل التحديات الأسبوعية',
      en: 'Complete weekly challenges',
      tr: 'Haftalık meydan okumaları tamamla',
      ur: 'ہفتہ وار چیلنجز مکمل کریں',
    },
  },
  {
    id: 'speed-demon',
    icon: '⚡',
    category: 'challenge',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'score', metric: 'fastest_story_time', operator: '<=', value: 60 }],
    name: {
      de: 'Geschwindigkeitsdämon',
      ar: 'شيطان السرعة',
      en: 'Speed Demon',
      tr: 'Hız Şeytanı',
      ur: 'تیز رفتار',
    },
    description: {
      de: 'Geschichte in unter 1 Minute abgeschlossen',
      ar: 'أكملت قصة في أقل من دقيقة',
      en: 'Complete story in under 1 minute',
      tr: '1 dakikadan kısa sürede hikaye tamamla',
      ur: '1 منٹ سے کم میں کہانی مکمل کریں',
    },
    hint: {
      de: 'Sei extrem schnell',
      ar: 'كن سريعًا جدًا',
      en: 'Be extremely fast',
      tr: 'Son derece hızlı ol',
      ur: 'انتہائی تیز ہوں',
    },
  },
  {
    id: 'perfectionist-challenge',
    icon: '💯',
    category: 'challenge',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'perfect_stories_no_hints', operator: '>=', value: 20 }],
    name: {
      de: 'Perfektionist-Herausforderung',
      ar: 'تحدي الكمالي',
      en: 'Perfectionist Challenge',
      tr: 'Mükemmeliyetçi Meydan Okuması',
      ur: 'کامل پسند چیلنج',
    },
    description: {
      de: '20 Geschichten ohne Hinweise perfekt abgeschlossen',
      ar: 'أكملت 20 قصة بشكل مثالي دون تلميحات',
      en: 'Complete 20 stories perfectly without hints',
      tr: 'İpucu olmadan 20 hikayeyi kusursuz tamamla',
      ur: 'اشارے کے بغیر 20 کہانیاں مکمل طور پر مکمل کریں',
    },
    hint: {
      de: 'Keine Hinweise verwenden',
      ar: 'لا تستخدم التلميحات',
      en: "Don't use hints",
      tr: 'İpucu kullanma',
      ur: 'اشارے استعمال نہ کریں',
    },
  },
  {
    id: 'early-riser',
    icon: '🌄',
    category: 'challenge',
    rarity: 'bronze',
    unlocked: false,
    starReward: RARITY_REWARDS.bronze,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'time', metric: 'reading_hour', operator: '<', value: 7 },
        { type: 'streak', metric: 'early_morning_streak', operator: '>=', value: 5 },
      ],
    }],
    name: {
      de: 'Früher Vogel',
      ar: 'طائر مبكر',
      en: 'Early Riser',
      tr: 'Erken Kalkan',
      ur: 'صبح سویرے اٹھنے والا',
    },
    description: {
      de: '5 Tage in Folge vor 7 Uhr gelesen',
      ar: 'قرأت قبل الساعة 7 صباحًا لمدة 5 أيام متتالية',
      en: 'Read before 7am for 5 days in a row',
      tr: '5 gün üst üste saat 07:00\'dan önce oku',
      ur: 'لگاتار 5 دن صبح 7 بجے سے پہلے پڑھیں',
    },
    hint: {
      de: 'Lies sehr früh morgens',
      ar: 'اقرأ في الصباح الباكر جدًا',
      en: 'Read very early in the morning',
      tr: 'Sabah çok erken oku',
      ur: 'صبح بہت جلدی پڑھیں',
    },
  },
  {
    id: 'midnight-reader',
    icon: '🌙',
    category: 'challenge',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'time', metric: 'reading_hour', operator: '>=', value: 23 },
        { type: 'count', metric: 'midnight_reads', operator: '>=', value: 10 },
      ],
    }],
    name: {
      de: 'Mitternachtsleser',
      ar: 'قارئ منتصف الليل',
      en: 'Midnight Reader',
      tr: 'Gece Yarısı Okuyucusu',
      ur: 'آدھی رات پڑھنے والا',
    },
    description: {
      de: '10 Geschichten nach 23 Uhr gelesen',
      ar: 'قرأت 10 قصص بعد الساعة 11 مساءً',
      en: 'Read 10 stories after 11pm',
      tr: 'Saat 23:00\'dan sonra 10 hikaye oku',
      ur: 'رات 11 بجے کے بعد 10 کہانیاں پڑھیں',
    },
    hint: {
      de: 'Lies spät nachts',
      ar: 'اقرأ في وقت متأخر من الليل',
      en: 'Read late at night',
      tr: 'Gece geç saatlerde oku',
      ur: 'رات دیر سے پڑھیں',
    },
  },
  {
    id: 'all-nighter',
    icon: '🌃',
    category: 'challenge',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'stories_in_one_session', operator: '>=', value: 10 }],
    name: {
      de: 'Durchmacher',
      ar: 'ساهر طوال الليل',
      en: 'All-Nighter',
      tr: 'Tüm Gece',
      ur: 'رات بھر جاگنے والا',
    },
    description: {
      de: '10 Geschichten in einer Sitzung gelesen',
      ar: 'قرأت 10 قصص في جلسة واحدة',
      en: 'Read 10 stories in one session',
      tr: 'Bir oturumda 10 hikaye oku',
      ur: 'ایک بیٹھک میں 10 کہانیاں پڑھیں',
    },
    hint: {
      de: 'Lies viele Geschichten nacheinander',
      ar: 'اقرأ العديد من القصص على التوالي',
      en: 'Read many stories in a row',
      tr: 'Arka arkaya birçok hikaye oku',
      ur: 'لگاتار بہت سی کہانیاں پڑھیں',
    },
  },
  {
    id: 'quiz-flawless',
    icon: '🎯',
    category: 'challenge',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'first_try_perfect_quizzes', operator: '>=', value: 25 }],
    name: {
      de: 'Quiz-Makellos',
      ar: 'اختبار خالٍ من العيوب',
      en: 'Quiz Flawless',
      tr: 'Kusursuz Test',
      ur: 'کوئز بے عیب',
    },
    description: {
      de: '25 perfekte Quiz beim ersten Versuch',
      ar: '25 اختبارًا مثاليًا من المحاولة الأولى',
      en: '25 perfect quizzes on first try',
      tr: 'İlk denemede 25 kusursuz test',
      ur: 'پہلی کوشش میں 25 کامل کوئز',
    },
    hint: {
      de: 'Sei von Anfang an perfekt',
      ar: 'كن مثاليًا من البداية',
      en: 'Be perfect from the start',
      tr: 'Baştan itibaren kusursuz ol',
      ur: 'شروع سے ہی کامل ہوں',
    },
  },
  {
    id: 'explorer-extraordinaire',
    icon: '🗺️',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'count', metric: 'all_locations_visited', operator: '==', value: true },
        { type: 'count', metric: 'all_treasures_found', operator: '==', value: true },
        { type: 'count', metric: 'all_characters_met', operator: '==', value: true },
      ],
    }],
    name: {
      de: 'Außergewöhnlicher Entdecker',
      ar: 'مستكشف استثنائي',
      en: 'Explorer Extraordinaire',
      tr: 'Olağanüstü Kaşif',
      ur: 'غیر معمولی کھوجی',
    },
    description: {
      de: 'Alle Orte, Schätze und Charaktere gefunden',
      ar: 'وجدت جميع الأماكن والكنوز والشخصيات',
      en: 'Found all locations, treasures, and characters',
      tr: 'Tüm yerleri, hazineleri ve karakterleri bul',
      ur: 'تمام مقامات، خزانے اور کردار تلاش کیے',
    },
    hint: {
      de: 'Erkunde alles vollständig',
      ar: 'استكشف كل شيء بالكامل',
      en: 'Explore everything completely',
      tr: 'Her şeyi tamamen keşfet',
      ur: 'ہر چیز مکمل طور پر دریافت کریں',
    },
  },
  {
    id: 'skill-tree-master',
    icon: '🌳',
    category: 'challenge',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'skill_tree_fully_unlocked', operator: '==', value: true }],
    name: {
      de: 'Fähigkeitsbaum-Meister',
      ar: 'سيد شجرة المهارات',
      en: 'Skill Tree Master',
      tr: 'Beceri Ağacı Ustası',
      ur: 'مہارت کے درخت ماسٹر',
    },
    description: {
      de: 'Gesamten Fähigkeitsbaum freigeschaltet',
      ar: 'فتحت شجرة المهارات بالكامل',
      en: 'Unlock entire skill tree',
      tr: 'Tüm beceri ağacını aç',
      ur: 'مکمل مہارت کا درخت کھولیں',
    },
    hint: {
      de: 'Schalte alle Fähigkeiten frei',
      ar: 'افتح جميع المهارات',
      en: 'Unlock all skills',
      tr: 'Tüm becerileri aç',
      ur: 'تمام مہارتیں کھولیں',
    },
  },
  {
    id: 'master-of-all-games',
    icon: '🎮',
    category: 'challenge',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'count', metric: 'memory_games_won', operator: '>=', value: 10 },
        { type: 'count', metric: 'puzzles_completed', operator: '>=', value: 10 },
        { type: 'count', metric: 'mazes_completed', operator: '>=', value: 10 },
        { type: 'count', metric: 'dance_games_perfect', operator: '>=', value: 10 },
      ],
    }],
    name: {
      de: 'Meister aller Spiele',
      ar: 'سيد جميع الألعاب',
      en: 'Master of All Games',
      tr: 'Tüm Oyunların Ustası',
      ur: 'تمام گیمز کا ماسٹر',
    },
    description: {
      de: 'Alle Spielarten gemeistert',
      ar: 'أتقنت جميع أنواع الألعاب',
      en: 'Master all game types',
      tr: 'Tüm oyun türlerinde ustalaş',
      ur: 'تمام گیم کی اقسام میں مہارت حاصل کریں',
    },
    hint: {
      de: 'Spiele alle verschiedenen Spiele',
      ar: 'العب جميع الألعاب المختلفة',
      en: 'Play all different games',
      tr: 'Tüm farklı oyunları oyna',
      ur: 'تمام مختلف گیمز کھیلیں',
    },
  },
  {
    id: 'creative-genius',
    icon: '🎨',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'count', metric: 'stories_created', operator: '>=', value: 10 },
        { type: 'count', metric: 'characters_designed', operator: '>=', value: 10 },
        { type: 'count', metric: 'compositions_created', operator: '>=', value: 10 },
        { type: 'count', metric: 'choreographies_created', operator: '>=', value: 5 },
        { type: 'count', metric: 'coloring_pages_completed', operator: '>=', value: 25 },
      ],
    }],
    name: {
      de: 'Kreatives Genie',
      ar: 'عبقري مبدع',
      en: 'Creative Genius',
      tr: 'Yaratıcı Dahi',
      ur: 'تخلیقی ذہین',
    },
    description: {
      de: 'Meistere alle kreativen Aktivitäten',
      ar: 'أتقن جميع الأنشطة الإبداعية',
      en: 'Master all creative activities',
      tr: 'Tüm yaratıcı faaliyetlerde ustalaş',
      ur: 'تمام تخلیقی سرگرمیوں میں مہارت حاصل کریں',
    },
    hint: {
      de: 'Nutze alle kreativen Werkzeuge',
      ar: 'استخدم جميع الأدوات الإبداعية',
      en: 'Use all creative tools',
      tr: 'Tüm yaratıcı araçları kullan',
      ur: 'تمام تخلیقی اوزار استعمال کریں',
    },
  },
  {
    id: 'ultimate-collector',
    icon: '🏆',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'count', metric: 'cards_collected', operator: '>=', value: 100 },
        { type: 'count', metric: 'shop_items_owned', operator: '>=', value: 50 },
        { type: 'count', metric: 'pets_adopted', operator: '>=', value: 3 },
        { type: 'count', metric: 'badges_earned', operator: '>=', value: 75 },
      ],
    }],
    name: {
      de: 'Ultimativer Sammler',
      ar: 'جامع نهائي',
      en: 'Ultimate Collector',
      tr: 'Nihai Koleksiyoncu',
      ur: 'حتمی جمع کرنے والا',
    },
    description: {
      de: 'Sammle alles',
      ar: 'اجمع كل شيء',
      en: 'Collect everything',
      tr: 'Her şeyi topla',
      ur: 'ہر چیز جمع کریں',
    },
    hint: {
      de: 'Sammle Karten, Artikel, Haustiere und Abzeichen',
      ar: 'اجمع البطاقات والعناصر والحيوانات الأليفة والشارات',
      en: 'Collect cards, items, pets, and badges',
      tr: 'Kartları, ürünleri, evcil hayvanları ve rozetleri topla',
      ur: 'کارڈز، اشیاء، پالتو جانور اور بیجز جمع کریں',
    },
  },
  {
    id: 'star-millionaire',
    icon: '💰',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{ type: 'count', metric: 'total_stars_earned', operator: '>=', value: 10000 }],
    name: {
      de: 'Sterne-Millionär',
      ar: 'مليونير النجوم',
      en: 'Star Millionaire',
      tr: 'Yıldız Milyoneri',
      ur: 'ستارہ کروڑ پتی',
    },
    description: {
      de: '10.000 Sterne verdient (gesamt)',
      ar: 'حصلت على 10,000 نجمة (إجمالي)',
      en: 'Earn 10,000 stars (total)',
      tr: '10.000 yıldız kazan (toplam)',
      ur: '10,000 ستارے کمائیں (کل)',
    },
    hint: {
      de: 'Verdiene viele Sterne',
      ar: 'اكسب الكثير من النجوم',
      en: 'Earn lots of stars',
      tr: 'Çok fazla yıldız kazan',
      ur: 'بہت سے ستارے کمائیں',
    },
  },
  {
    id: 'level-100',
    icon: '💯',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{ type: 'count', metric: 'player_level', operator: '>=', value: 100 }],
    name: {
      de: 'Level 100',
      ar: 'المستوى 100',
      en: 'Level 100',
      tr: 'Seviye 100',
      ur: 'سطح 100',
    },
    description: {
      de: 'Erreiche Level 100',
      ar: 'وصل إلى المستوى 100',
      en: 'Reach level 100',
      tr: 'Seviye 100\'e ulaş',
      ur: 'سطح 100 تک پہنچیں',
    },
    hint: {
      de: 'Sammle viel XP',
      ar: 'اجمع الكثير من XP',
      en: 'Collect lots of XP',
      tr: 'Çok fazla XP topla',
      ur: 'بہت سا XP جمع کریں',
    },
  },
];

// Export combined array for convenience
export const ADDITIONAL_BADGES = [...ACTIVITY_BADGES, ...CHALLENGE_BADGES];
