/**
 * Badge Collection System - Extra Badges
 * Additional badges to reach 100+
 */

import type { Badge } from './badge-system';
import { RARITY_REWARDS } from './badge-system';

export const EXTRA_BADGES: Badge[] = [
  // More skill-specific badges
  {
    id: 'skill-master-problem-solving',
    icon: '🔍',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_problem_solving', operator: '>=', value: 5 }],
    name: {
      de: 'Problemlösungs-Meister',
      ar: 'سيد حل المشكلات',
      en: 'Problem-Solving Master',
      tr: 'Problem Çözme Ustası',
      ur: 'مسئلہ حل کرنے کا ماسٹر',
    },
    description: {
      de: '5 Problemlösungs-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص حل المشكلات',
      en: 'Master 5 problem-solving stories',
      tr: '5 problem çözme hikayesinde ustalaş',
      ur: '5 مسئلہ حل کرنے کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Problemlösung ab',
      ar: 'أكمل قصصًا عن حل المشكلات',
      en: 'Complete problem-solving stories',
      tr: 'Problem çözme hikayelerini tamamla',
      ur: 'مسئلہ حل کرنے کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-decision-making',
    icon: '🤔',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_decision_making', operator: '>=', value: 5 }],
    name: {
      de: 'Entscheidungs-Meister',
      ar: 'سيد اتخاذ القرار',
      en: 'Decision-Making Master',
      tr: 'Karar Verme Ustası',
      ur: 'فیصلہ سازی ماسٹر',
    },
    description: {
      de: '5 Entscheidungsfindungs-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص اتخاذ القرار',
      en: 'Master 5 decision-making stories',
      tr: '5 karar verme hikayesinde ustalaş',
      ur: '5 فیصلہ سازی کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Entscheidungsfindung ab',
      ar: 'أكمل قصصًا عن اتخاذ القرار',
      en: 'Complete decision-making stories',
      tr: 'Karar verme hikayelerini tamamla',
      ur: 'فیصلہ سازی کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-critical-thinking',
    icon: '💡',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_critical_thinking', operator: '>=', value: 5 }],
    name: {
      de: 'Kritisches-Denken-Meister',
      ar: 'سيد التفكير النقدي',
      en: 'Critical-Thinking Master',
      tr: 'Eleştirel Düşünme Ustası',
      ur: 'تنقیدی سوچ ماسٹر',
    },
    description: {
      de: '5 kritisches-Denken-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص التفكير النقدي',
      en: 'Master 5 critical-thinking stories',
      tr: '5 eleştirel düşünme hikayesinde ustalaş',
      ur: '5 تنقیدی سوچ کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über kritisches Denken ab',
      ar: 'أكمل قصصًا عن التفكير النقدي',
      en: 'Complete critical-thinking stories',
      tr: 'Eleştirel düşünme hikayelerini tamamla',
      ur: 'تنقیدی سوچ کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-adaptability',
    icon: '🌿',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_adaptability', operator: '>=', value: 5 }],
    name: {
      de: 'Anpassungsfähigkeits-Meister',
      ar: 'سيد التكيف',
      en: 'Adaptability Master',
      tr: 'Uyum Yeteneği Ustası',
      ur: 'موافقت ماسٹر',
    },
    description: {
      de: '5 Anpassungsfähigkeits-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص التكيف',
      en: 'Master 5 adaptability stories',
      tr: '5 uyum yeteneği hikayesinde ustalaş',
      ur: '5 موافقت کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Anpassungsfähigkeit ab',
      ar: 'أكمل قصصًا عن التكيف',
      en: 'Complete adaptability stories',
      tr: 'Uyum yeteneği hikayelerini tamamla',
      ur: 'موافقت کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-communication',
    icon: '💬',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_communication', operator: '>=', value: 5 }],
    name: {
      de: 'Kommunikations-Meister',
      ar: 'سيد التواصل',
      en: 'Communication Master',
      tr: 'İletişim Ustası',
      ur: 'رابطہ ماسٹر',
    },
    description: {
      de: '5 Kommunikations-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص التواصل',
      en: 'Master 5 communication stories',
      tr: '5 iletişim hikayesinde ustalaş',
      ur: '5 رابطہ کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Kommunikation ab',
      ar: 'أكمل قصصًا عن التواصل',
      en: 'Complete communication stories',
      tr: 'İletişim hikayelerini tamamla',
      ur: 'رابطہ کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-leadership',
    icon: '👑',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_leadership', operator: '>=', value: 5 }],
    name: {
      de: 'Führungs-Meister',
      ar: 'سيد القيادة',
      en: 'Leadership Master',
      tr: 'Liderlik Ustası',
      ur: 'قیادت ماسٹر',
    },
    description: {
      de: '5 Führungs-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص القيادة',
      en: 'Master 5 leadership stories',
      tr: '5 liderlik hikayesinde ustalaş',
      ur: '5 قیادت کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Führung ab',
      ar: 'أكمل قصصًا عن القيادة',
      en: 'Complete leadership stories',
      tr: 'Liderlik hikayelerini tamamla',
      ur: 'قیادت کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-persistence',
    icon: '💪',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_persistence', operator: '>=', value: 5 }],
    name: {
      de: 'Durchhaltevermögens-Meister',
      ar: 'سيد المثابرة',
      en: 'Persistence Master',
      tr: 'Sebat Ustası',
      ur: 'استقامت ماسٹر',
    },
    description: {
      de: '5 Durchhaltevermögens-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص المثابرة',
      en: 'Master 5 persistence stories',
      tr: '5 sebat hikayesinde ustalaş',
      ur: '5 استقامت کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Durchhaltevermögen ab',
      ar: 'أكمل قصصًا عن المثابرة',
      en: 'Complete persistence stories',
      tr: 'Sebat hikayelerini tamamla',
      ur: 'استقامت کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'skill-master-conflict-resolution',
    icon: '🤝',
    category: 'skill',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'skill_conflict_resolution', operator: '>=', value: 5 }],
    name: {
      de: 'Konfliktlösungs-Meister',
      ar: 'سيد حل النزاعات',
      en: 'Conflict-Resolution Master',
      tr: 'Çatışma Çözümü Ustası',
      ur: 'تنازعات حل کرنے کا ماسٹر',
    },
    description: {
      de: '5 Konfliktlösungs-Geschichten gemeistert',
      ar: 'أتقنت 5 قصص حل النزاعات',
      en: 'Master 5 conflict-resolution stories',
      tr: '5 çatışma çözümü hikayesinde ustalaş',
      ur: '5 تنازعات حل کرنے کی کہانیاں مکمل کریں',
    },
    hint: {
      de: 'Schließe Geschichten über Konfliktlösung ab',
      ar: 'أكمل قصصًا عن حل النزاعات',
      en: 'Complete conflict-resolution stories',
      tr: 'Çatışma çözümü hikayelerini tamamla',
      ur: 'تنازعات حل کرنے کی کہانیاں مکمل کریں',
    },
  },
  {
    id: 'completionist-supreme',
    icon: '👑💎',
    category: 'challenge',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond * 2,
    conditions: [{ type: 'count', metric: 'badges_earned', operator: '>=', value: 100 }],
    name: {
      de: 'Absoluter Vollender',
      ar: 'المكمل المطلق',
      en: 'Supreme Completionist',
      tr: 'Yüce Tamamlayıcı',
      ur: 'اعلیٰ مکمل کرنے والا',
    },
    description: {
      de: '100 Abzeichen verdient!',
      ar: 'حصلت على 100 شارة!',
      en: 'Earn 100 badges!',
      tr: '100 rozet kazan!',
      ur: '100 بیجز حاصل کریں!',
    },
    hint: {
      de: 'Verdiene alle anderen Abzeichen',
      ar: 'احصل على جميع الشارات الأخرى',
      en: 'Earn all other badges',
      tr: 'Diğer tüm rozetleri kazan',
      ur: 'تمام دیگر بیجز حاصل کریں',
    },
  },
];
