/**
 * Badge Collection System - Special Badges
 * Seasonal and Secret badges
 */

import type { Badge } from './badge-system';
import { RARITY_REWARDS } from './badge-system';

export const SEASONAL_BADGES: Badge[] = [
  // ============================================
  // SEASONAL BADGES (10 badges)
  // ============================================
  {
    id: 'new-year-reader',
    icon: '🎆',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_new_year', operator: '==', value: true }],
    name: {
      de: 'Neujahrs-Leser',
      ar: 'قارئ رأس السنة',
      en: 'New Year Reader',
      tr: 'Yılbaşı Okuyucusu',
      ur: 'نیا سال پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte am Neujahrstag gelesen',
      ar: 'قرأت قصة في يوم رأس السنة',
      en: 'Read a story on New Year\'s Day',
      tr: 'Yılbaşı günü bir hikaye oku',
      ur: 'نئے سال کے دن ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies am 1. Januar',
      ar: 'اقرأ في 1 يناير',
      en: 'Read on January 1st',
      tr: '1 Ocak\'ta oku',
      ur: '1 جنوری کو پڑھیں',
    },
  },
  {
    id: 'valentines-reader',
    icon: '💝',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_valentines', operator: '==', value: true }],
    name: {
      de: 'Valentinstags-Leser',
      ar: 'قارئ عيد الحب',
      en: 'Valentine\'s Reader',
      tr: 'Sevgililer Günü Okuyucusu',
      ur: 'ویلنٹائن پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte am Valentinstag gelesen',
      ar: 'قرأت قصة في عيد الحب',
      en: 'Read a story on Valentine\'s Day',
      tr: 'Sevgililer Günü\'nde bir hikaye oku',
      ur: 'ویلنٹائن ڈے پر ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies am 14. Februar',
      ar: 'اقرأ في 14 فبراير',
      en: 'Read on February 14th',
      tr: '14 Şubat\'ta oku',
      ur: '14 فروری کو پڑھیں',
    },
  },
  {
    id: 'easter-reader',
    icon: '🐰',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_easter', operator: '==', value: true }],
    name: {
      de: 'Osterleser',
      ar: 'قارئ عيد الفصح',
      en: 'Easter Reader',
      tr: 'Paskalya Okuyucusu',
      ur: 'ایسٹر پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte an Ostern gelesen',
      ar: 'قرأت قصة في عيد الفصح',
      en: 'Read a story on Easter',
      tr: 'Paskalya\'da bir hikaye oku',
      ur: 'ایسٹر پر ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies an Ostern',
      ar: 'اقرأ في عيد الفصح',
      en: 'Read on Easter',
      tr: 'Paskalya\'da oku',
      ur: 'ایسٹر پر پڑھیں',
    },
  },
  {
    id: 'summer-reader',
    icon: '☀️',
    category: 'seasonal',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'summer_stories_read', operator: '>=', value: 20 }],
    name: {
      de: 'Sommer-Leser',
      ar: 'قارئ الصيف',
      en: 'Summer Reader',
      tr: 'Yaz Okuyucusu',
      ur: 'گرمی پڑھنے والا',
    },
    description: {
      de: '20 Geschichten im Sommer gelesen',
      ar: 'قرأت 20 قصة في الصيف',
      en: 'Read 20 stories in summer',
      tr: 'Yazın 20 hikaye oku',
      ur: 'گرمیوں میں 20 کہانیاں پڑھیں',
    },
    hint: {
      de: 'Lies viel im Sommer (Juni-August)',
      ar: 'اقرأ كثيرًا في الصيف (يونيو-أغسطس)',
      en: 'Read a lot in summer (June-August)',
      tr: 'Yazın çok oku (Haziran-Ağustos)',
      ur: 'گرمیوں میں بہت پڑھیں (جون-اگست)',
    },
  },
  {
    id: 'halloween-reader',
    icon: '🎃',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_halloween', operator: '==', value: true }],
    name: {
      de: 'Halloween-Leser',
      ar: 'قارئ الهالوين',
      en: 'Halloween Reader',
      tr: 'Cadılar Bayramı Okuyucusu',
      ur: 'ہیلووین پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte an Halloween gelesen',
      ar: 'قرأت قصة في الهالوين',
      en: 'Read a story on Halloween',
      tr: 'Cadılar Bayramı\'nda bir hikaye oku',
      ur: 'ہیلووین پر ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies am 31. Oktober',
      ar: 'اقرأ في 31 أكتوبر',
      en: 'Read on October 31st',
      tr: '31 Ekim\'de oku',
      ur: '31 اکتوبر کو پڑھیں',
    },
  },
  {
    id: 'christmas-reader',
    icon: '🎄',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_christmas', operator: '==', value: true }],
    name: {
      de: 'Weihnachtsleser',
      ar: 'قارئ عيد الميلاد',
      en: 'Christmas Reader',
      tr: 'Noel Okuyucusu',
      ur: 'کرسمس پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte an Weihnachten gelesen',
      ar: 'قرأت قصة في عيد الميلاد',
      en: 'Read a story on Christmas',
      tr: 'Noel\'de bir hikaye oku',
      ur: 'کرسمس پر ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies am 24. oder 25. Dezember',
      ar: 'اقرأ في 24 أو 25 ديسمبر',
      en: 'Read on December 24th or 25th',
      tr: '24 veya 25 Aralık\'ta oku',
      ur: '24 یا 25 دسمبر کو پڑھیں',
    },
  },
  {
    id: 'back-to-school',
    icon: '🎒',
    category: 'seasonal',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'date', metric: 'is_back_to_school', operator: '==', value: true }],
    name: {
      de: 'Zurück zur Schule',
      ar: 'العودة إلى المدرسة',
      en: 'Back to School',
      tr: 'Okula Dönüş',
      ur: 'اسکول واپسی',
    },
    description: {
      de: 'Eine Geschichte in der ersten Schulwoche gelesen',
      ar: 'قرأت قصة في الأسبوع الأول من المدرسة',
      en: 'Read a story in first week of school',
      tr: 'Okulun ilk haftasında bir hikaye oku',
      ur: 'اسکول کے پہلے ہفتے میں ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies Anfang September',
      ar: 'اقرأ في بداية سبتمبر',
      en: 'Read in early September',
      tr: 'Eylül başında oku',
      ur: 'ستمبر کے شروع میں پڑھیں',
    },
  },
  {
    id: 'birthday-reader',
    icon: '🎂',
    category: 'seasonal',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'date', metric: 'is_user_birthday', operator: '==', value: true }],
    name: {
      de: 'Geburtstags-Leser',
      ar: 'قارئ عيد الميلاد',
      en: 'Birthday Reader',
      tr: 'Doğum Günü Okuyucusu',
      ur: 'سالگرہ پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte an deinem Geburtstag gelesen',
      ar: 'قرأت قصة في عيد ميلادك',
      en: 'Read a story on your birthday',
      tr: 'Doğum günün bir hikaye oku',
      ur: 'اپنی سالگرہ پر ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies an deinem Geburtstag',
      ar: 'اقرأ في عيد ميلادك',
      en: 'Read on your birthday',
      tr: 'Doğum günün oku',
      ur: 'اپنی سالگرہ پر پڑھیں',
    },
  },
  {
    id: 'anniversary-year',
    icon: '🎊',
    category: 'seasonal',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{ type: 'date', metric: 'days_since_first_visit', operator: '>=', value: 365 }],
    name: {
      de: 'Ein Jahr dabei',
      ar: 'سنة واحدة معنا',
      en: 'One Year Anniversary',
      tr: 'Bir Yıl Yıldönümü',
      ur: 'ایک سال کی سالگرہ',
    },
    description: {
      de: 'Ein Jahr aktiv dabei',
      ar: 'سنة واحدة نشطة',
      en: 'One year active',
      tr: 'Bir yıl aktif',
      ur: 'ایک سال فعال',
    },
    hint: {
      de: 'Komm ein Jahr lang zurück',
      ar: 'عد لمدة عام',
      en: 'Come back for one year',
      tr: 'Bir yıl geri gel',
      ur: 'ایک سال واپس آئیں',
    },
  },
  {
    id: 'ramadan-reader',
    icon: '🌙',
    category: 'seasonal',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'date', metric: 'is_ramadan', operator: '==', value: true }],
    name: {
      de: 'Ramadan-Leser',
      ar: 'قارئ رمضان',
      en: 'Ramadan Reader',
      tr: 'Ramazan Okuyucusu',
      ur: 'رمضان پڑھنے والا',
    },
    description: {
      de: 'Eine Geschichte während Ramadan gelesen',
      ar: 'قرأت قصة خلال شهر رمضان',
      en: 'Read a story during Ramadan',
      tr: 'Ramazan ayında bir hikaye oku',
      ur: 'رمضان کے دوران ایک کہانی پڑھیں',
    },
    hint: {
      de: 'Lies während des Ramadan',
      ar: 'اقرأ خلال شهر رمضان',
      en: 'Read during Ramadan',
      tr: 'Ramazan ayında oku',
      ur: 'رمضان کے دوران پڑھیں',
    },
  },
];

export const SECRET_BADGES: Badge[] = [
  // ============================================
  // SECRET BADGES (10 badges)
  // ============================================
  {
    id: 'easter-egg-hunter',
    icon: '🥚',
    category: 'secret',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'easter_eggs_found', operator: '>=', value: 10 }],
    name: {
      de: 'Ostereier-Jäger',
      ar: 'صائد بيض عيد الفصح',
      en: 'Easter Egg Hunter',
      tr: 'Paskalya Yumurtası Avcısı',
      ur: 'ایسٹر انڈے کا شکاری',
    },
    description: {
      de: '10 versteckte Ostereier gefunden',
      ar: 'وجدت 10 بيضات عيد فصح مخفية',
      en: 'Find 10 hidden easter eggs',
      tr: '10 gizli paskalya yumurtası bul',
      ur: '10 چھپے ہوئے ایسٹر انڈے تلاش کریں',
    },
    hint: {
      de: '???',
      ar: '؟؟؟',
      en: '???',
      tr: '???',
      ur: '؟؟؟',
    },
  },
  {
    id: 'konami-code',
    icon: '🎮',
    category: 'secret',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'konami_code_entered', operator: '==', value: true }],
    name: {
      de: 'Konami-Code',
      ar: 'كود كونامي',
      en: 'Konami Code',
      tr: 'Konami Kodu',
      ur: 'کونامی کوڈ',
    },
    description: {
      de: 'Den geheimen Konami-Code eingegeben',
      ar: 'أدخلت كود كونامي السري',
      en: 'Enter the secret Konami code',
      tr: 'Gizli Konami kodunu gir',
      ur: 'خفیہ کونامی کوڈ درج کریں',
    },
    hint: {
      de: '↑ ↑ ↓ ↓ ← → ← → B A',
      ar: '↑ ↑ ↓ ↓ ← → ← → B A',
      en: '↑ ↑ ↓ ↓ ← → ← → B A',
      tr: '↑ ↑ ↓ ↓ ← → ← → B A',
      ur: '↑ ↑ ↓ ↓ ← → ← → B A',
    },
  },
  {
    id: 'secret-level',
    icon: '🚪',
    category: 'secret',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{ type: 'count', metric: 'secret_level_found', operator: '==', value: true }],
    name: {
      de: 'Geheimes Level',
      ar: 'المستوى السري',
      en: 'Secret Level',
      tr: 'Gizli Seviye',
      ur: 'خفیہ سطح',
    },
    description: {
      de: 'Das geheime Level gefunden',
      ar: 'وجدت المستوى السري',
      en: 'Find the secret level',
      tr: 'Gizli seviyeyi bul',
      ur: 'خفیہ سطح تلاش کریں',
    },
    hint: {
      de: 'Klicke auf das ??? Symbol',
      ar: 'انقر على رمز ؟؟؟',
      en: 'Click on the ??? symbol',
      tr: '??? Simgesine tıkla',
      ur: '??? علامت پر کلک کریں',
    },
  },
  {
    id: 'developer-console',
    icon: '👨‍💻',
    category: 'secret',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'console_opened', operator: '==', value: true }],
    name: {
      de: 'Entwickler-Konsole',
      ar: 'وحدة تحكم المطور',
      en: 'Developer Console',
      tr: 'Geliştirici Konsolu',
      ur: 'ڈویلپر کنسول',
    },
    description: {
      de: 'Die Entwickler-Konsole geöffnet',
      ar: 'فتحت وحدة تحكم المطور',
      en: 'Open the developer console',
      tr: 'Geliştirici konsolunu aç',
      ur: 'ڈویلپر کنسول کھولیں',
    },
    hint: {
      de: 'Drücke F12',
      ar: 'اضغط F12',
      en: 'Press F12',
      tr: 'F12\'ye bas',
      ur: 'F12 دبائیں',
    },
  },
  {
    id: 'midnight-mystery',
    icon: '🌌',
    category: 'secret',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{
      type: 'composite',
      logic: 'AND',
      conditions: [
        { type: 'time', metric: 'exact_hour', operator: '==', value: 0 },
        { type: 'time', metric: 'exact_minute', operator: '==', value: 0 },
      ],
    }],
    name: {
      de: 'Mitternachts-Mysterium',
      ar: 'لغز منتصف الليل',
      en: 'Midnight Mystery',
      tr: 'Gece Yarısı Gizemi',
      ur: 'آدھی رات کا راز',
    },
    description: {
      de: 'Genau um Mitternacht online',
      ar: 'متصل بالضبط في منتصف الليل',
      en: 'Online exactly at midnight',
      tr: 'Tam gece yarısı çevrimiçi',
      ur: 'بالکل آدھی رات میں آن لائن',
    },
    hint: {
      de: '00:00 Uhr',
      ar: '00:00',
      en: '00:00',
      tr: '00:00',
      ur: '00:00',
    },
  },
  {
    id: 'triple-numbers',
    icon: '🎰',
    category: 'secret',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'triple_number_stars', operator: '==', value: true }],
    name: {
      de: 'Dreifach-Zahlen',
      ar: 'أرقام ثلاثية',
      en: 'Triple Numbers',
      tr: 'Üçlü Sayılar',
      ur: 'تین گنا نمبر',
    },
    description: {
      de: 'Sterne mit dreifachen Zahlen (111, 222, etc.)',
      ar: 'نجوم بأرقام ثلاثية (111، 222، إلخ)',
      en: 'Stars with triple numbers (111, 222, etc.)',
      tr: 'Üçlü sayılı yıldızlar (111, 222, vb.)',
      ur: 'تین گنا نمبروں والے ستارے (111، 222، وغیرہ)',
    },
    hint: {
      de: 'Erreiche 111, 222, 333... Sterne',
      ar: 'احصل على 111، 222، 333... نجمة',
      en: 'Reach 111, 222, 333... stars',
      tr: '111, 222, 333... yıldıza ulaş',
      ur: '111، 222، 333... ستارے حاصل کریں',
    },
  },
  {
    id: 'lucky-seven',
    icon: '🍀',
    category: 'secret',
    rarity: 'gold',
    unlocked: false,
    starReward: RARITY_REWARDS.gold,
    conditions: [{ type: 'count', metric: 'stories_read', operator: '==', value: 77 }],
    name: {
      de: 'Glückliche Sieben',
      ar: 'سبعة محظوظة',
      en: 'Lucky Seven',
      tr: 'Şanslı Yedi',
      ur: 'خوش قسمت سات',
    },
    description: {
      de: 'Genau 77 Geschichten gelesen',
      ar: 'قرأت بالضبط 77 قصة',
      en: 'Read exactly 77 stories',
      tr: 'Tam olarak 77 hikaye oku',
      ur: 'بالکل 77 کہانیاں پڑھیں',
    },
    hint: {
      de: '7 ist eine Glückszahl',
      ar: '7 رقم محظوظ',
      en: '7 is a lucky number',
      tr: '7 şanslı bir sayı',
      ur: '7 ایک خوش قسمت نمبر ہے',
    },
  },
  {
    id: 'click-master',
    icon: '🖱️',
    category: 'secret',
    rarity: 'silver',
    unlocked: false,
    starReward: RARITY_REWARDS.silver,
    conditions: [{ type: 'count', metric: 'character_clicks', operator: '>=', value: 100 }],
    name: {
      de: 'Klick-Meister',
      ar: 'سيد النقرات',
      en: 'Click Master',
      tr: 'Tıklama Ustası',
      ur: 'کلک ماسٹر',
    },
    description: {
      de: '100 Mal auf Charaktere geklickt',
      ar: 'نقرت على الشخصيات 100 مرة',
      en: 'Click on characters 100 times',
      tr: 'Karakterlere 100 kez tıkla',
      ur: 'کرداروں پر 100 بار کلک کریں',
    },
    hint: {
      de: 'Klicke auf alle Charaktere',
      ar: 'انقر على جميع الشخصيات',
      en: 'Click on all characters',
      tr: 'Tüm karakterlere tıkla',
      ur: 'تمام کرداروں پر کلک کریں',
    },
  },
  {
    id: 'rainbow-connection',
    icon: '🌈',
    category: 'secret',
    rarity: 'platinum',
    unlocked: false,
    starReward: RARITY_REWARDS.platinum,
    conditions: [{ type: 'count', metric: 'rainbow_sequence_completed', operator: '==', value: true }],
    name: {
      de: 'Regenbogen-Verbindung',
      ar: 'اتصال قوس قزح',
      en: 'Rainbow Connection',
      tr: 'Gökkuşağı Bağlantısı',
      ur: 'قوس قزح کنکشن',
    },
    description: {
      de: 'Die Regenbogen-Sequenz abgeschlossen',
      ar: 'أكملت تسلسل قوس قزح',
      en: 'Complete the rainbow sequence',
      tr: 'Gökkuşağı dizisini tamamla',
      ur: 'قوس قزح کی ترتیب مکمل کریں',
    },
    hint: {
      de: 'Folge den Farben des Regenbogens',
      ar: 'اتبع ألوان قوس قزح',
      en: 'Follow the colors of the rainbow',
      tr: 'Gökkuşağının renklerini takip et',
      ur: 'قوس قزح کے رنگوں کی پیروی کریں',
    },
  },
  {
    id: 'time-traveler',
    icon: '⏰',
    category: 'secret',
    rarity: 'diamond',
    unlocked: false,
    starReward: RARITY_REWARDS.diamond,
    conditions: [{ type: 'count', metric: 'visited_all_hours', operator: '==', value: true }],
    name: {
      de: 'Zeitreisender',
      ar: 'مسافر عبر الزمن',
      en: 'Time Traveler',
      tr: 'Zaman Yolcusu',
      ur: 'وقت کا مسافر',
    },
    description: {
      de: 'Zu allen 24 Stunden des Tages online gewesen',
      ar: 'كنت متصلاً في جميع ساعات اليوم الـ 24',
      en: 'Been online at all 24 hours of the day',
      tr: 'Günün 24 saatinde çevrimiçi ol',
      ur: 'دن کے تمام 24 گھنٹوں میں آن لائن رہیں',
    },
    hint: {
      de: 'Besuche zu jeder Tagesstunde',
      ar: 'قم بالزيارة في كل ساعة من اليوم',
      en: 'Visit at every hour of the day',
      tr: 'Günün her saatinde ziyaret et',
      ur: 'دن کے ہر گھنٹے میں دیکھیں',
    },
  },
];

// Export combined array for convenience
export const SPECIAL_BADGES = [...SEASONAL_BADGES, ...SECRET_BADGES];
